defaults:
  # Common setup.
  - setup
  # This file.
  - _self_
  # - optional override:

model:
  name: unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit

load_in_4bit: True
max_seq_length: -1
dtype: null
